### ISSUE TITLE
"https://" issue

### ISSUE THREAD

**Issue by iamdual** [atarantini/wpbf#33]
If url start with "https://", I keep getting this error:
ERROR - URL Error on: http://https://xxxxxxx.xxx/wp-login.php

**Comment by atarantini** [comment]
Thanks for the report, I will take a look ASAP!

**Comment by atarantini** [comment]
Done, released [1.0.1](https://github.com/atarantini/wpbf/tree/1.0.1) already merged on master. Pull and test if you want, and thanks for the bug report!
